"""needs reload

Revision ID: 14347d316581
Revises: a39859622f80
Create Date: 2025-02-21 14:35:49.873766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14347d316581'
down_revision = 'a39859622f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_knowledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_reload', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_knowledge', schema=None) as batch_op:
        batch_op.drop_column('needs_reload')

    # ### end Alembic commands ###
