"""Remove assistant_id from base_knowledge

Revision ID: 23d00a5ef875
Revises: 
Create Date: 2025-02-21 10:56:17.183886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23d00a5ef875'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_knowledge', schema=None) as batch_op:
        batch_op.drop_constraint('base_knowledge_ibfk_1', type_='foreignkey')
        batch_op.drop_column('assistant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_knowledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('base_knowledge_ibfk_1', 'assistant', ['assistant_id'], ['id'])

    # ### end Alembic commands ###
