"""Add progress tracking to task status

Revision ID: 38008254f1dd
Revises: 14347d316581
Create Date: 2025-02-21 14:39:37.537229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38008254f1dd'
down_revision = '14347d316581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_status_base_knowledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_steps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status_message', sa.String(length=255), nullable=True))
        batch_op.alter_column('base_knowledge_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_status_base_knowledge', schema=None) as batch_op:
        batch_op.alter_column('base_knowledge_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('status_message')
        batch_op.drop_column('total_steps')
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
