"""Add last_loaded field to BaseKnowledge

Revision ID: a39859622f80
Revises: 23d00a5ef875
Create Date: 2025-02-21 14:26:12.759379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39859622f80'
down_revision = '23d00a5ef875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_knowledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_loaded', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_knowledge', schema=None) as batch_op:
        batch_op.drop_column('last_loaded')

    # ### end Alembic commands ###
