"""assistenti llm

Revision ID: ee7e8b6c7ed0
Revises: 38008254f1dd
Create Date: 2025-02-25 10:57:44.520696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7e8b6c7ed0'
down_revision = '38008254f1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_model', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('llm_temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('llm_max_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.drop_column('llm_max_tokens')
        batch_op.drop_column('llm_temperature')
        batch_op.drop_column('llm_model')

    # ### end Alembic commands ###
