services:
  backend:
    build:
      context: ./autocally-backend
    volumes:
      - ./autocally-backend:/app/src
      - ./server.cert:/app/src/certs/server.cert:ro
      - ./server.key:/app/src/certs/server.key:ro
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    environment:
      - REDIS_PORT=6380
      - SSL_CERT=/app/src/certs/server.cert
      - SSL_KEY=/app/src/certs/server.key
    networks:
      app_network:
        ipv4_address: 172.20.0.11

  celery_worker:
    build:
      context: ./autocally-backend
    command: /bin/sh -c "cd /app/src && celery -A celery_worker.celery worker --pool=eventlet --loglevel=info"
    volumes:
      - ./autocally-backend:/app/src
    env_file:
      - .env
    depends_on:
      - backend
      - mysql
      - redis
    environment:
      - REDIS_PORT=6380
      - DB_HOST=mysql
    networks:
      app_network:
        ipv4_address: 172.20.0.15

  frontend:
    build:
      context: ./autocally-frontend
    volumes:
      - type: bind
        source: ./autocally-frontend
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
      - ./autocally-backend/certs:/app/certs:ro  # Mount the same certificates
      - ./server.key:/app/server.key:ro
      - ./server.cert:/app/server.cert:ro
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=https://172.20.0.14:6969
    working_dir: /app
    networks:
      app_network:
        ipv4_address: 172.20.0.10

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    networks:
      app_network:
        ipv4_address: 172.20.0.13

  mysql:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Admin$$00'
      MYSQL_DATABASE: autocally
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      app_network:
        ipv4_address: 172.20.0.12

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./server.cert:/etc/nginx/ssl/server.cert:ro
      - ./server.key:/etc/nginx/ssl/server.key:ro
      - ./autocally-frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "6969:6969"
    depends_on:
      - frontend
      - backend
    networks:
      app_network:
        ipv4_address: 172.20.0.14

volumes:
  redis_data:
  mysql_data:
  node_modules:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16